os:
  - linux
  - osx
language: perl6
perl6:
  - latest
before_install:
  - sudo apt-get update
  - sudo apt-get install acpid
install:
  - rakudobrew build-panda
  - panda --notests installdeps .
  - panda install Config::From
script:
  - perl6 -MPanda::Builder -e 'Panda::Builder.build(~$*CWD)'
  - PERL6LIB=$PWD/lib prove -e perl6 -vr t/
sudo: false
